#!/usr/bin/env python3
from Crypto.Cipher import AES
from sys import argv, exit
import sys
import numpy as np

def main():
	

	if len(argv) != 7:
		print("not enough arguments")
		return

	keything=sys.argv[1]
	keyfile=sys.argv[2]
	ithing=sys.argv[3]
	encryptedfile=sys.argv[4]
	othing=sys.argv[5]
	outputfile=sys.argv[6]

	if keything !="-k":
		print(keything + " is an unknown operation")
		return
	if ithing !="-i":
		print(ithing + " is an unknown operation")
		return
	if othing !="-o":
		print(othing + " is an unknown operation")
		return

	p=open(keyfile,"r")
	hex_key=p.read()
	p.close()
	key=bytes.fromhex(hex_key)
	decipher = AES.new(key, AES.MODE_ECB)

	o=open(outputfile,'wb')
	final=[]

	with open(encryptedfile, 'rb') as f:
		iv=bytes(f.read(16))
		intiv=int.from_bytes(iv, byteorder='big')
		intiv+=1
		while 1:
			msg=bytearray(f.read(16))
			if msg == bytes('','utf-8'):
				break
			test=intiv.to_bytes(16,byteorder='big')
			iv2=bytearray(decipher.encrypt(test))
			for x in range(len(msg)):
				final.append(iv2[x] ^ msg[x])
				print(chr(final[x]))
			intiv+=1

	o.write(bytes(final))

if __name__ == "__main__":
	exit(main())
