#!/usr/bin/env python3

from sys import argv,exit
from Crypto.Cipher import AES
from Crypto import Random
from multiprocessing import Pool
import os.path

def main():
	if len(argv) != 7:
		print("Usage: ./ctr-enc.py -k <key file> -i <input file> -o <output file>")
		raise Exception("Bad Command Line Args")

	fin = open(argv[2],"r")
	hexKey = fin.read()
	fin.close()
	fout = open(argv[6],"wb+")

	counter = 0
	messageBlocks = []
	fin = open(argv[4],"rb")
	while 1:
		temp = bytearray(fin.read(16)) 
		if temp == bytes('','utf-8'):
			break
		messageBlocks.append(temp)
		counter += 1
	fin.close()	

	IV = bytes(os.urandom(16))
	IVint=int.from_bytes(IV,byteorder='big')
	IVint += 1
	cipher = AES.new(bytes.fromhex(hexKey),AES.MODE_ECB)
	fout.write(bytes(IV))

	for i in range (0,counter):
		interMed = bytearray(cipher.encrypt(IVint.to_bytes(16,byteorder='big')))
		for j in range (0,len(messageBlocks[i])):
			messageBlocks[i][j] ^= interMed[i]
		fout.write(messageBlocks[i])
		IVint+=1

	fout.close()
#	with Pool(4) as p:
#		cipherTexts = [[p.apply(encrypt,args=(x,y,hexKey)) for x in messageBlocks] for y in range(int.from_bytes(IV,byteorder='big')+1,int.from_bytes(IV,byteorder='big') + len(messageBlocks) + 1)]


def encrypt(msg,IV,hexKey):
	cipher = AES.new(bytes.fromhex(hexKey),AES.MODE_ECB)
	interMed = bytearray(cipher.encrypt(IV.to_bytes(16,byteorder='big')))
	for i in range (0,len(msg)):
		msg[i] ^= interMed[i]
	return msg	
	


if __name__ == "__main__":
	exit(main())
