#!/usr/bin/env python3
from Crypto.Cipher import AES
from sys import argv, exit
import sys
import numpy as np

def main():

	keyfile=sys.argv[1]
	encryptedfile=sys.argv[2]
	outputfile=sys.argv[3]

	f=open(keyfile,"r")
	hex_key=f.read()
	key=bytes.fromhex(hex_key)
	decipher = AES.new(key, AES.MODE_ECB)

	o=open(outputfile,'w')
	output=[1]*16
	final=""

	with open(encryptedfile, 'rb') as f:
		iv=f.read(16)
		intiv=int.from_bytes(iv, byteorder='big')
		intiv+=1
		intiv=np.dtype(int16)
		while 1:
			msg=bytearray(f.read(16))
			if msg == bytes('','utf-8'):
				break
			iv2=bytearray(decipher.decrypt(intiv))
			for x in range(16):
				output[x]=iv2[x] ^ msg[x] 
				final+=(chr(output[x]))
			intiv+=1

	shred=ord(final[len(final)-1])
	if shred == 0:
		o.write(final)
	else:
		final = final[:-shred]
		print(shred)
		o.write(final)
	




if __name__ == "__main__":
	exit(main())
