#!/usr/bin/env python3

from sys import argv,exit
import os.path

def main():
#	if len(argv) != 7:
#		print("Usage: ./rsa-enc -k <key-file> -i <input-file> -o <output-file>")
#		raise Exception("Bad Command Line Args")
	
	fin = open(argv[2],"r")
	vals = fin.read().splitlines()
	fin.close()
	
	numBitsN = int(vals[0])
	N = int(vals[1])
	e = int(vals[2])
	r = numBitsN / 2

	fin = open(argv[4],"r")
	msg = fin.read()
	fin.close()

	element = []
	element.append(0x0)
	element.append(0x2)

	for i in range (0,int(r / 8)):
		randomByte = bytearray(os.urandom(1))
		if(randomByte[0] == 0x0):
			i -= 8
		else:
			element.append(randomByte[0])

	if r % 8:	#I dont think this would make sense for it to not be a multiple of 8?
		randomByte = bytearray(os.urandom(1))
		while randomByte == 0x0:
			randomByte = bytearray(os.urandom(1))
		#do some sort of damn bit shift ???

	element.append(0x0)
	for value in bytearray.fromhex(msg):
		element.append(value)

	fout = open(argv[6],"w")
	fout.write(str(int.from_bytes(element,byteorder='big') ** e % N))
	
	fout.close()
	
	print(element)
	print(int.from_bytes(element,byteorder='big'))
	print((int.from_bytes(element,byteorder='big') ** e) % N)


if __name__ == "__main__":
	exit(main())
