#!/usr/bin/env python

from sys import argv,exit
import os.path

def main():
#	if len(argv) != 7:
#		print("Usage: ./rsa-enc -k <key-file> -i <input-file> -o <output-file>")
#		raise Exception("Bad Command Line Args")
	
	fin = open(argv[2],"r")
	vals = fin.read().splitlines()
	fin.close()
	
	numBitsN = int(vals[0])
	N = int(vals[1])
	e = int(vals[2])
	r = numBitsN / 2

	fin = open(argv[4],"rb")
	msg = bytearray(fin.read())
	fin.close()

	print(r)

if __name__ == "__main__":
	exit(main())
