#!/usr/bin/env python3

from sys import argv, exit
from Crypto.Cipher import PKCS1_OAEP
from Crypto.PublicKey import RSA
from cryptography.hazmat.backends import default_backend
from cryptography.hazmat.primitives.ciphers import (
	Cipher, algorithms, modes
)
from ecdsa import SigningKey
import os.path, ecdsa

def main():
#	if len(argv) != 9:
#		print("Usage: ./lock -d <directory> -p <action-pub-key> -r <action-priv-key> -s <action-subject>")
#		raise Exception("Bad Command Line Args")

	algorithm,subject,rsaKey = readPub(argv[4])

	if subject != argv[8]:
		print("Subjects do not match!")
		exit()
	
	#Gen random 256 AES key
	AESkey = os.urandom(32)
	print(AESkey)
	iv = os.urandom(12)
	encryptor = Cipher(
		algorithms.AES(AESkey),
		modes.GCM(iv),
		backend=default_backend()
	).encryptor()

	#Uses RSA to encrypt the AES key and store it in keyfile
	cipher = PKCS1_OAEP.new(rsaKey)
	AESCiphertext = cipher.encrypt(AESkey)
	keyfile = argv[2] + "/keyfile"
	fout = open(keyfile,"wb")
	fout.write(AESCiphertext)
	fout.close()

	algorithm,ecKeyData = readPriv(argv[6])

	sig = ecKeyData.sign(AESCiphertext)
	keyfileSig = argv[2] + "/keyfile.sig"
	fout = open(keyfileSig, "wb")
	fout.write(sig)
	fout.close()

	if argv[2] == "." or argv[2] == "./" or argv[2] == "./.":
		print("DON'T RUN THIS IN THE CURRENT DIR!!")
		exit()

#	for root,dirs,files in os.walk(argv[2], topdown=True):
#		for name in files:
#			filename = os.path.join(root,name)
#			fin = open(filename, "rb")
#			contents = fin.read()
#			fin.close()
#			fout = open(filename, "wb")
#			ciphertext = encryptor.update(contents) + encryptor.finalize()
#			fout.write(encryptor.tag)
#			fout.write("\n")
#			fout.write(iv)
#			fout.write("\n")
#			fout.write(ciphertext)
#			fout.close()
			#Basically, open every file, read it all in, encrypt it, spit it back out with the tag and iv i guess?

def readPub(filename):
	f = open(filename, "r")
	lastline = f.read().split()
	if lastline[-2] == 'rsa':
		pubKey = RSA.importKey(open(filename, "r").read())

	else:
		pubKey = ecdsa.VerifyingKey.from_pem(open(filename, "r").read())

	f.close()
	return [lastline[-2], lastline[-1], pubKey]

def readPriv(filename):
	f = open(filename, "r")
	lastline = f.read().split()
	if lastline[-1] == 'rsa':
		privKey = RSA.importKey(open(filename, "r").read())	

	else:
		privKey = ecdsa.SigningKey.from_pem(open(filename, "r").read())

	f.close()
	return [lastline[-1], privKey]


if __name__ == "__main__":
	exit(main())
